Make semcode buildable with rustc 1.86
Currently semcode requires the latest and greatest rust with some
experimental features and can't be built with a more stable rust
version (1.86).

An attempt to build it using rustc 1.86 generates a number of build
errors, e.g.:
```
error[E0658]: use of unstable library feature `unsigned_is_multiple_of`
    --> .../src/index.crates.io-1949cf8c6b5b557f/lance-datagen-0.39.0/src/generator.rs:2013:32
     |
2013 |         if !batch_size_bytes.0.is_multiple_of(bytes_per_row) {
     |                                ^^^^^^^^^^^^^^
     |
     = note: see issue #128101 <https://github.com/rust-lang/rust/issues/128101> for more information

For more information about this error, try `rustc --explain E0658`.
```

With this change it builds successfully.
No functional change intended.

Signed-off-by: Roman Gushchin <roman.gushchin@linux.dev>